version: "3.9"

# STUDENT 2 MICROSERVICE — its own independent project.
# Ports: frontend 3002, backend 5002, database 6002 (internal == external).

services:
  frontend:
    build: ./frontend
    container_name: accomodation-fe
    environment:
      - PORT=3002
      - BACKEND_SERVICE_URL=http://accomodation-be:5002
    ports:
      - "3002:3002"
    depends_on:
      - backend
    networks:
      - internal

  backend:
    build: ./backend
    container_name: accomodation-be
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DATABASE_SERVICE_URL=http://database:6002
      - DESTINATION_SERVICE_URL=http://destination-db:6001
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=qwen2.5:7b
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database
    networks:
      - internal
      - microservices-net

  database:
    build: ./database
    container_name: accomodation-db
    ports:
      - "6002:6002"
    environment:
      - PORT=6002
      - DB_FILE=/data/accommodation-db.sqlite
    volumes:
      - accomodation-db-data:/data
    networks:
      - internal
      - microservices-net

networks:
  internal:
    driver: bridge
  microservices-net:
    external: true

volumes:
  accomodation-db-data:
